### ISSUE TITLE
极客训练营第一周作业

### ISSUE THREAD

**Issue by KyrieIrving** [algorithm009-class01/algorithm009-class01#7]
#学号:G20200343060283
#姓名:章超群
#班级:1班
#语言:javascript
#作业链接:https://github.com/KyrieIrving/algorithm009-class01/tree/master/Week_01
#总结链接:https://github.com/KyrieIrving/algorithm009-class01/tree/master/Week_01

**Comment by luochunfeng163** [comment]
#学号:G20200343060221
#姓名:罗春风
#班级:1班
#语言:c++
#作业链接:https://github.com/luochunfeng163/algorithm009-class01/tree/master/Week_01
#总结链接:https://github.com/luochunfeng163/algorithm009-class01/tree/master/Week_01
